services:

  db-dev:
    build: 
      context: ./db
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: users
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'db4dev$'
      MYSQL_ROOT_PASSWORD: 'db4dev$'
    volumes:
      - my-sql:/var/lib/mysql
    networks:
      - api
    
  api-dev:
    build:
      context: ./app
    ports:
      - "8081:5000"
    environment:
      - DB_HOST=db-dev
      - DB_USER=admin
      - DB_PASSWORD=db4dev$
      - DB_NAME=users
    networks:
      - api
    depends_on:
      - db-dev
  
networks:
  api:
    driver: bridge

volumes:
  my-sql: