services:

  db-test:
    build: 
      context: ./db
    image: spdx/db
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: users
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'db4test$'
      MYSQL_ROOT_PASSWORD: 'db4test$'
    volumes:
      - my-sql-test:/var/lib/mysql
    networks:
      - api2
    
  api-test:
    build:
      context: ./app
    image: spdx/api
    ports:
      - "8082:5000"
    environment:
      - DB_HOST=db-test
      - DB_USER=admin
      - DB_PASSWORD=db4test$
      - DB_NAME=users
    networks:
      - api2
    depends_on:
      - db-test

networks:
    api2:
      driver: bridge
  
volumes:
    my-sql-test: